[features]
seeds = false
skip-lint = false

[programs.localnet]
serenium_s = "7tGHjvmtx3dSXXjHqDQvPES4P1wGrmywXcQxKke4ihnT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/jonar/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
